In [1]:
import scanpy as sc
import pandas as pd

/nfs/software/stegle/users/acuomo/conda-envs/myscanpy/lib/python3.7/site-packages/anndata/_core/anndata.py:21: FutureWarning: pandas.core.index is deprecated and will be removed in a future version.  The public classes are available in the top-level namespace.
  from pandas.core.index import RangeIndex

In [2]:
filename = "/hps/nobackup/stegle/users/acuomo/all_scripts/covid/cov19_w_regev_tsankov_whitsett_kaminski_krasnow_misharin_new_schultze_schultze_falk_rawlins_xavier_meyer_new_spence_barbry_seibold_shalek_nawijnNasal.h5ad"

In [3]:
adatafull = sc.read(filename)

In [4]:
adatafull

AnnData object with n_obs × n_vars = 1227421 × 3
    obs: 'donor', 'sample', 'age', 'sex', 'smoking', 'pack_years', 'anatomical_region', 'total_counts', 'ann_level_1', 'ann_level_2', 'ann_level_3', 'ann_level_4', 'ann_level_5', 'dataset', 'lung_vs_nasal', 'smoking_status', 'last_author', 'sample_last_author_name'

In [5]:
adatafull.obs.head(2)

,donor,sample,age,sex,smoking,pack_years,anatomical_region,total_counts,ann_level_1,ann_level_2,ann_level_3,ann_level_4,ann_level_5,dataset,lung_vs_nasal,smoking_status,last_author,sample_last_author_name
TCTATTGCACGGTTTA-1-HCATisStab7659969_368C_Madissoon____,368C,368C,57.5,male,active,NaN,parenchyma,3256.0,Immune,Lymphoid,B cell lineage,B cells,4_B cells,Sanger_Meyer_2019Madissoon,lung,True,Meyer_a,Meyer_a_04
CATATGGTCGTCTGAA-1-HCATisStab7646034_367C_Madissoon____,367C,367C,67.5,male,former,NaN,parenchyma,3580.0,Immune,Lymphoid,T cell lineage,CD4 T cells,4_CD4 T cells,Sanger_Meyer_2019Madissoon,lung,True,Meyer_a,Meyer_a_03

In [6]:
adatafull.var

Empty DataFrame
Columns: []
Index: [ACE2, TMPRSS2, CTSL]

In [7]:
adata = adatafull

In [8]:
adata.obs.age = adata.obs.age.astype(float)

In [9]:
adata.obs.dtypes

donor                      category
sample                     category
age                         float64
sex                        category
smoking                    category
pack_years                  float64
anatomical_region          category
total_counts                float64
ann_level_1                category
ann_level_2                category
ann_level_3                category
ann_level_4                category
ann_level_5                category
dataset                    category
lung_vs_nasal              category
smoking_status             category
last_author                category
sample_last_author_name    category
dtype: object

In [10]:
adata.obs.dataset.value_counts()

tsankov                                374010
meyer_new                              117535
kaminski                                95303
spence_fetal                            78401
barbry                                  77969
krasnow_10x                             65651
Sanger_Meyer_2019Madissoon              56711
rawlins                                 53409
regev_healthy_nucseq                    43527
Northwestern_Misharin_2018Reyfman       41778
seibold                                 36248
Xu_Whitsett_Peds_10X                    34185
Vanderbilt_Kropski_bioRxivHabermann     31644
xavier                                  25726
Pittsburgh_Lafyatis_2019Morse           22898
schultze                                22641
Misharin_new                            18753
Groningen_Nawijn_2019VieiraBraga        18197
shalek                                   7603
Xu_Whitsett_Peds_dropseq                 3267
schultze_falk                            1965
Name: dataset, dtype: int64

In [11]:
adata.X[:10,:10].A

array([[ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  3.,  1.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0., 12.],
       [ 0.,  0.,  3.],
       [ 0.,  0.,  0.]], dtype=float32)

In [12]:
pd.crosstab(adata.obs.dataset, adata.obs.ann_level_3)

ann_level_3,1_Endothelial,1_Epithelial,1_Immune,1_New,1_Stroma,1_Unicorns and artifacts,2_Airway epithelium,2_Alveolar epithelium,2_Basaloid,2_Blood vessels,...,Muscle_LAMC3,Myofibroblasts,Neutrophilic,None,Rare,Secretory,Submucosal Secretory,T cell lineage,Venous,Venous smooth muscle
dataset,,,,,,,,,,,,,,,,,,,,,
Groningen_Nawijn_2019VieiraBraga,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,54,7549,171,40,254,0
Misharin_new,0,0,0,0,0,59,0,0,0,0,...,0,0,0,0,84,1292,447,386,0,0
Northwestern_Misharin_2018Reyfman,0,0,0,0,210,512,0,0,0,569,...,0,0,0,1893,0,386,0,0,0,0
Pittsburgh_Lafyatis_2019Morse,0,0,0,0,723,0,0,0,0,1437,...,0,0,0,0,0,310,0,2704,0,0
Sanger_Meyer_2019Madissoon,0,0,0,0,0,0,0,0,0,2624,...,0,0,0,5349,0,0,0,13506,0,0
Vanderbilt_Kropski_bioRxivHabermann,0,0,0,0,0,0,0,0,0,2761,...,0,196,0,0,0,620,0,2923,0,0
Xu_Whitsett_Peds_10X,2665,516,12349,0,8631,0,0,0,0,0,...,0,0,0,0,0,1201,0,0,0,0
Xu_Whitsett_Peds_dropseq,763,0,305,0,1783,0,105,0,0,0,...,0,0,0,0,0,0,0,0,0,0
barbry,0,0,0,0,0,0,0,0,0,2722,...,0,0,0,0,244,17712,3625,0,0,0
kaminski,0,0,0,0,0,0,0,0,0,0,...,0,204,0,0,19,327,0,8787,226,0
krasnow_10x,0,0,0,0,0,0,0,0,0,0,...,0,248,0,0,22,1090,515,7512,1155,0
meyer_new,0,0,0,0,0,0,0,0,0,3873,...,792,0,0,0,60,1733,2355,17442,5551,656
rawlins,0,0,0,0,5021,0,0,0,0,3885,...,0,0,34,0,130,395,0,2034,0,0
regev_healthy_nucseq,0,0,0,0,0,0,0,0,0,3303,...,0,0,0,0,0,693,0,1156,0,0
schultze,0,0,0,0,0,0,96,0,0,0,...,0,0,325,0,0,0,0,2201,0,0
schultze_falk,0,0,0,0,0,20,0,66,0,0,...,0,0,35,0,0,123,0,512,0,0
seibold,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,280,2979,2318,0,0,0
shalek,0,0,0,0,0,0,0,0,0,0,...,0,0,294,0,0,6799,0,125,0,0
spence_fetal,2385,0,0,0,6645,5235,2946,0,0,0,...,0,0,0,0,806,0,0,3166,0,2434
tsankov,14564,0,0,0,0,0,0,0,0,0,...,0,0,0,0,2860,0,33646,0,0,0
xavier,0,0,0,174,0,86,0,0,226,0,...,0,1328,0,0,0,2317,0,970,707,0