In [1]:
import mofax as mfx
import pandas as pd

In [2]:
# m = mfx.mofa_model("/hps/nobackup/stegle/users/acuomo/all_scripts/struct_LMM2/sc_neuroseq/mofa20_pseudocells4.hdf5")
m = mfx.mofa_model("/hps/nobackup/stegle/users/acuomo/all_scripts/struct_LMM2/sc_neuroseq/mofa20_pseudocells4_wo_outliers.hdf5")
df = pd.DataFrame(m.get_factors())

In [3]:
df.shape #

(9219, 20)

In [4]:
df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,1.666456,0.589292,-1.218032,0.533271,-0.114718,-0.700450,-0.872012,-0.722233,0.145421,0.255173,-0.153703,0.046562,0.933561,-0.303333,-1.420607,0.376046,-1.375035,-1.321022,0.036285,-0.523784
1,1.793275,-1.089708,0.516194,0.303165,-0.370706,-0.636298,1.135930,0.246662,-0.323239,-0.328950,0.297498,0.106488,1.434802,0.173501,1.149061,-0.520607,0.887738,-0.130147,0.941842,0.661152
2,1.460173,-0.920466,0.433373,0.838284,0.041792,-0.349312,-0.566510,0.033184,-0.294749,1.647099,-0.244315,1.193586,0.234430,1.367610,-1.354624,-0.435662,-0.001934,0.004343,-0.109958,-0.029995
3,2.135217,0.007668,-0.340678,0.169422,-0.487267,-0.947462,0.234383,-0.442354,0.556301,0.434645,0.031946,0.581785,0.673075,0.188795,-1.246520,1.037264,-0.689319,-0.844010,1.148122,0.371534
4,-0.299618,-1.471801,-0.559841,-0.287968,-0.071475,-0.094412,-0.972754,0.581462,-1.232076,-0.334227,-0.414754,1.178597,0.021825,-0.070580,-0.086396,0.656685,0.007250,-0.023221,-1.766547,-1.082093

In [13]:
df.to_csv("/hps/nobackup/stegle/users/acuomo/all_scripts/struct_LMM2/sc_neuroseq/May2021/mofa_logcounts_model_factors.csv")

In [5]:
df_weights = pd.DataFrame(data = m.get_weights(), index=m.features['scRNAseq'])
df_weights.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
HES4,-1.198950,-0.606049,-0.577342,-0.716888,-0.533292,0.295580,0.249432,0.163630,0.254428,-0.156335,0.087714,-0.166740,0.068922,0.161526,-0.102259,-0.233439,-0.050599,0.074216,-0.020277,-0.032060
CHD5,-1.032320,0.007728,-0.137244,-0.150031,0.208921,0.264613,0.032799,-0.152735,0.294096,-0.062163,0.126378,-0.003141,0.226869,0.088431,0.086042,0.119956,-0.035348,0.076231,0.096732,0.003000
ACOT7,-1.173171,-0.559427,-0.055223,0.202518,-0.365982,0.296520,-0.030886,-0.104327,-0.115282,-0.229920,-0.279929,-0.052676,-0.040348,0.052374,0.071150,0.048453,0.049514,-0.083195,-0.133744,0.018522
UTS2,-1.218231,0.348608,0.047887,-0.176592,0.020540,-0.497684,0.466281,0.032669,0.013730,0.507385,-0.020020,0.451065,-0.061071,0.186243,0.164919,0.279448,0.076698,-0.070841,-0.010143,0.192440
ENO1,-1.055883,0.258639,-0.106439,0.010039,-0.283510,0.134990,-0.017225,-0.046407,-0.034836,-0.246875,-0.184860,0.128133,-0.095102,-0.054555,-0.000744,-0.062849,0.003176,0.092197,-0.212683,-0.115482

In [6]:
df_weights.shape

(500, 20)

In [15]:
df_weights.to_csv("/hps/nobackup/stegle/users/acuomo/all_scripts/struct_LMM2/sc_neuroseq/May2021/mofa_weights.csv")